services:
  mosquitto:
    image: eclipse-mosquitto:latest
    container_name: mosquitto-mqtt
    ports:
      - "1883:1883" # MQTT port
      - "9001:9001" # WebSocket port
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log
    restart: unless-stopped
    networks:
      - mqtt-network

  publisher:
    build: .
    container_name: mqtt-publisher
    command: python -u publisher.py
    depends_on:
      - mosquitto
    restart: unless-stopped
    networks:
      - mqtt-network

  subscriber:
    build: .
    container_name: mqtt-subscriber
    command: python -u subscriber.py
    depends_on:
      - mosquitto
    restart: unless-stopped
    networks:
      - mqtt-network

networks:
  mqtt-network:
    driver: bridge
